
package com.mycompany.practica2;

/**
 *
 * @author linux
 */
public class VisualizarPedido extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarPedido
     */
    public VisualizarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblVehiculo1 = new javax.swing.JLabel();
        lblDistancia1 = new javax.swing.JLabel();
        btnEnviar1 = new javax.swing.JButton();
        lblVehiculo2 = new javax.swing.JLabel();
        lblDistancia2 = new javax.swing.JLabel();
        btnEnviar2 = new javax.swing.JButton();
        lblVehiculo3 = new javax.swing.JLabel();
        lblDistancia3 = new javax.swing.JLabel();
        btnEnviar3 = new javax.swing.JButton();
        btnEnviarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Visualización de Pedidos");

        lblVehiculo1.setText("Vehículo 1");

        lblDistancia1.setText("Distancia");

        btnEnviar1.setText("Enviar");

        lblVehiculo2.setText("Vehículo 2");

        lblDistancia2.setText("Distancia");

        btnEnviar2.setText("Enviar");

        lblVehiculo3.setText("Vehículo 3");

        lblDistancia3.setText("Distancia");

        btnEnviar3.setText("Enviar");

        btnEnviarTodos.setBackground(new java.awt.Color(234, 234, 255));
        btnEnviarTodos.setText("Enviar Todos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDistancia1)
                    .addComponent(btnEnviar1)
                    .addComponent(lblVehiculo1)
                    .addComponent(lblDistancia2)
                    .addComponent(btnEnviar2)
                    .addComponent(lblVehiculo2)
                    .addComponent(lblDistancia3)
                    .addComponent(btnEnviar3)
                    .addComponent(lblVehiculo3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(btnEnviarTodos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnEnviarTodos))
                .addGap(26, 26, 26)
                .addComponent(lblVehiculo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDistancia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviar1)
                .addGap(40, 40, 40)
                .addComponent(lblVehiculo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDistancia2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviar2)
                .addGap(51, 51, 51)
                .addComponent(lblVehiculo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDistancia3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviar3)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar1;
    private javax.swing.JButton btnEnviar2;
    private javax.swing.JButton btnEnviar3;
    private javax.swing.JButton btnEnviarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDistancia1;
    private javax.swing.JLabel lblDistancia2;
    private javax.swing.JLabel lblDistancia3;
    private javax.swing.JLabel lblVehiculo1;
    private javax.swing.JLabel lblVehiculo2;
    private javax.swing.JLabel lblVehiculo3;
    // End of variables declaration//GEN-END:variables
}
